### ISSUE TITLE
unsuccessful job

### ISSUE THREAD

**Issue by norazlan** [workerholic/workerholic#85]
I'm using ruby on rails and integrated workerholic with activejob and ran workerholic in project root folder as suggested in doc. but in workerholic log it shown:

> ERROR: Failed: your job from class NewsletterJob was unsuccessful because of the folloing error: undefined method `constantize' for NewsletterJob:Class
> Did you mean?  constants => undefined method `constantize' for NewsletterJob:Class
> Did you mean?  constants. Retrying in 10 secs...

**Comment by antoineLeclercq** [comment]
Hi @norazlan, thanks for attempting to use Workerholic with `ActiveJob`! The integration with Rails is potentially limited to a specific Rails version. 
FYI, this project is not maintained anymore. It was originally created as a support to teach other developers how to build a multithreaded/multiprocess background job processor (https://www.youtube.com/watch?v=BnTT01k1Ztg).
If you are looking for a production ready, multithreaded, background job processor written in Ruby, I highly recommend Sidekiq (https://github.com/mperham/sidekiq).

**Comment by norazlan** [comment]
Thanks for the reply.
